name: CI/CD Pipeline
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test-and-train:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      MLFLOW_ARTIFACT_ROOT: "gs://mlops-course-wide-link-461605-p9-unique/mlflow-artifacts"
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Pytest for Data and Model Validation
      run: |
        python -m pytest tests/test_data_validation.py -v
        python -m pytest tests/test_model_evaluation.py -v
      
    - name: Authenticate with GCP for MLflow Artifacts
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    - name: Setup CML for reporting
      uses: iterative/setup-cml@v1
    - name: Run Training and Evaluation
      run: |
        python src/data_loader.py
        python src/train_model.py
        python src/evaluate_model.py
    - name: Generate CML Report
      run: |
        echo "## 📊 Model Evaluation Results" > report.md
        echo "" >> report.md
        echo "### Confusion Matrix" >> report.md
        echo '![](./models/confusion_matrix.png)' >> report.md
        echo "" >> report.md
        echo "### SHAP Summary Plot (Virginica)" >> report.md
        echo '![](./models/shap_summary_plot_virginica.png)' >> report.md
        echo "" >> report.md
        echo "Detailed logs and artifacts are available in the [MLflow UI](${{ secrets.MLFLOW_TRACKING_URI }})." >> report.md
    - name: Create or Update CML Comment on Pull Request
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cml comment create report.md
